#              AquaIcons developed by @Sxntido
#             This plugin was previously Emotes

# List of variables:
#  <empty> - An empty space is created
#  <center> - Messages will be in the center of the chat
# * %aquaicons_name% - Preview icon name
# * %aquaicons_trigger% - Preview the icon trigger
# * %aquaicons_icon% - Preview the icon
# * %aquaicons_permission% - Preview icon permission

# * Support Colors & HEX: https://www.birdflop.com/resources/rgb/
# * https://github.com/Sxntido - https://github.com/aquaticstudios

list:
  title-chat:
    - "<empty>"
    - "<center>&b&lAquaIcons &7(v1.0.0)"
    - "<center>&fPlugin created by &3@Sxntido"
    - "<empty>"
  no-icons:
    - "<center>&cNo icons found in &7icons.yml"
    - "<empty>"
  format-list:
    - " &7● &fTrigger: &a%aquaicons_trigger% &7| &fIcon: %aquaicons_icon% &7(%aquaicons_permission%)"
    - "<empty>"

messages:
  reload: "&aThe files have been uploaded successfully"
  new-icon: "&aA new icon was created &7(%aquaicons_name% - %aquaicons_trigger%)"
  already-name: "&cThis name already exists in &7icons.yml"
  already-trigger: "&cThis trigger already exists in &7icons.yml"
  unknown: "&cThe command you execute does not exist"
  how-to-create: "&c/aquaicons create <name> <trigger> <icon> <permission>"
  no-permission: "&cYou don't have permission execute this command"
  list-permission: "&cYou need to have permission &3[aquaicons.list]"