#                                                           Developed by Sxntido
#                                                     (Aquatic Studios @ (C) 2016-2024)

name: AquaIcons
version: '1.0'
author: 'Sxntido'

api-version: '1.13'
main: team.aquatic.studios.AquaIcons
description: 'All rights reserved by Aquatic Studios'

softdepend:
  - LuckPerms
  - PlaceholderAPI

commands:
  aquaicons:
    description: Command execute